version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true

  build:
    commands:
      - echo Build phase - no ETL logic yet

artifacts:
  files:
    - '**/*'
