version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt || true
      - pip install pyspark

  build:
    commands:
      - echo Checking syntax of ETL scripts...
      - python -m py_compile etl/*.py

artifacts:
  files:
    - '**/*'

